spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ai-fitness-recommendation-db
      database: ai-fitness-recommendation-db
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: activity-processor-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.fitness.aiservice.model.Activity
        spring.json.trusted.packages: "*"

kafka:
  topic:
    name: activity-events

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8083

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent
    key: AIzaSyAyk_RZInxj3LR3DrRRvRHGe_R_1jay1CE
